name: "hifetch"
version: "1.0.0"
description: "Host Information Fetch."
homepage: "https://github.com/ming2k/hifetch"
source:
  - uri: "https://github.com/ming2k/hifetch/archive/refs/tags/v0.0.1.tar.gz"
    checksum: "sha256:3e1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

# license: "MIT"
# dependencies:
#   - "libfoo >= 1.2.3"
#   - "libbar == 2.0.0"
# build:
#   commands:
#     - "./configure --prefix=/usr"
#     - "make"
#     - "make install"
maintainers:
  - name: "John Doe"
    email: "johndoe@example.com"
